---
title: "Creating Range Maps For Bats of The Pacific Northwest"
author:   
  - name: Trent VanHawkins
    affiliation: On Belay Statistical Consulting
    corresponding: true
  - name: Beth Ward
    affiliation: Oregon State University-Cascades
  - name: Tom Rodhouse
    affiliation: National Park Service
    degrees: PhD
format: html
bibliography: references.bib
csl: nature.csl
---

# Background

The Northwestern Hub for Bat Population Research and Monitoring (Northwest Bat Hub) began efforts at annual summer occupancy surveys for the 15 endemic bat species to the Pacific Northwest in 2016 as a regional member of the North American Bat Monitoring Program (NABat). This effort has led to the collection of a robust species occurrence dataset–currently spanning eight years–which has contributed to national efforts at analyzing population-level trends at the national level. [@udell] At a regional level, the Northwest Bat Hub has also produced many publications influencing study design,[@reichert2021; @rodhouse2017] data analysis, [@irvine2018] and conservation management.[@rodhouse2019; @rodhouse2021]

Initial monitoring efforts began in Oregon but have since expanded to include partners in Washington (2018) and Idaho (2020). As a result, regional analyses have focused primarily on Oregon and Washington. The Northwest Bat Hub and it's partners now have three years of vetted summer acoustic monitoring data which include Idaho, and are uniquely positioned to expand analyses as well.

-   Paragraph about Idaho joining in 2020 and strengthening the need for regional range maps.

    -   I.e Why do we need to make these range maps?

    -   How do the complement the tools that the Bat Hub already has?

-   Introducing... MaxEnt and how we plan to use it.

In this report, we will describe our approach to creating range maps for bat species in the three-state region of Oregon, Washington, and Idaho using the Maximum Entropy (MaxEnt) machine learning method. We then demonstrate how our approach can be flexibly implemented as a straight-forward extension to existing Bat Hub protocols. Finally, we discuss how collaborators might interpret and leverage model results in decision-making processes to support bat conservation.

# The Approach

## Why use MaxEnt?

Species Distribution Models (SDMs) are a part of a growing field of spatiotemporal models that leverage advancements in Machine Learning (ML) and Artificial Intelligence (AI). The Maximum Entropy (MaxEnt) @phillips2017a method has become particularly popular due to its ability to handle presence-only data (e.g. the data generated by NABat acoustic monitoring efforts) and its availability through open-source releases of the original java application @phillipsc and approximations in statistical modeling software ‘R’@kass2021a. We propose that we can leverage this openly available software to build a user-friendly extension of the Northwest Bat Hub’s data management pipeline that will efficiently provide visual data insights and summaries to its partners.

Briefly, MaxEnt works to make predictions about the probability of species occurrence across a study area given a set of vetted observations and a set of rasterized explanatory variables, also termed *environmental covariates.* The spatial resolution of the resulting predictions is determined by the spatial resolution of the available environmental covariates. In the context of this report, the study are of interest is the three-state region of Oregon, Washington, and Idaho. Species observation records were obtained from the Northwest Bat Hub's vetted acoustic monitoring records and environmental covariates (Table 1) were determined through literature review[@udell; @rodhouse2019; @rodhouse2021]. An in-depth explanation and motivation for the use of MaxEnt for ecological modeling purposes can be found in Elith et al., 2011 @elith2011.

## The Data

To recreate this analysis, three files are required:

1.  Species observations

2.  Rasterized environmental covariates

3.  A Shapefile of the study area

-   Where can these files be found?

-   Code chunks for properly formatting them and EDA?

-   Preparing data for analysis by MaxEnt

## Running the MaxEnt Model

-   Briefly give some details about model parameters (RM, feature types, etc...)

-   Code for serializing the maxent model.

# Viewing and Interpreting Range Maps

-   Figure containing all range maps

-   Figure for each range map may be found in the appendix

-   Brief explanation of the definition of 'occurrence probability'

-   Where can you find these results?

# Discussion & Future Directions

-   What are some of the drawbacks of MaxEnt?

-   What are other questions the bat hub is interested in answering?

-   How may these questions be answered using trend analysis?

# References

::: {#refs}
:::

# Appendix

## Model Diagnostics

## Expanded Results

## Code Appendix 
